package pgn

import (
	"fmt"
)

// Nag represents a numeric annotation glyph.
type Nag int

// String returns the common representation of the NAG if it has one (!, ?, !?,
// +-, -+, ...). Otherwise it returns $<nag> ($56, $123, ...).
func (n Nag) String() string {
	if int(n) >= len(nagData) || nagData[n].str == "" {
		return fmt.Sprintf("$%d", n)
	}
	return nagData[n].str
}

// Description returns a short description explaining the NAG.
func (n Nag) Description() string {
	if int(n) >= len(nagData) {
		return fmt.Sprintf("$%d: non-standard NAG", n)
	}
	return nagData[n].desc
}

var nagData = []struct {
	str  string
	desc string
}{
	0:   {"", "null annotation"},
	1:   {"!", "good move"},
	2:   {"?", "poor move"},
	3:   {"!!", "very good move"},
	4:   {"??", "very poor move"},
	5:   {"!?", "speculative move"},
	6:   {"?!", "questionable move"},
	7:   {"□", "forced move (all others lose quickly)"},
	8:   {"", "singular move (no reasonable alternatives)"},
	9:   {"", "worst move"},
	10:  {"=", "drawish position"},
	11:  {"", "equal chances, quiet position"},
	12:  {"", "equal chances, active position"},
	13:  {"∞", "unclear position"},
	14:  {"⩲", "white has a slight advantage"},
	15:  {"⩱", "black has a slight advantage"},
	16:  {"±", "white has a moderate advantage"},
	17:  {"∓", "black has a moderate advantage"},
	18:  {"+-", "white has a decisive advantage"},
	19:  {"-+", "black has a decisive advantage"},
	20:  {"+--", "white has a crushing advantage (black should resign)"},
	21:  {"--+", "black has a crushing advantage (white should resign)"},
	22:  {"", "white is in zugzwang"},
	23:  {"", "black is in zugzwang"},
	24:  {"", "white has a slight space advantage"},
	25:  {"", "black has a slight space advantage"},
	26:  {"", "white has a moderate space advantage"},
	27:  {"", "black has a moderate space advantage"},
	28:  {"", "white has a decisive space advantage"},
	29:  {"", "black has a decisive space advantage"},
	30:  {"", "white has a slight time (development) advantage"},
	31:  {"", "black has a slight time (development) advantage"},
	32:  {"", "white has a moderate time (development) advantage"},
	33:  {"", "black has a moderate time (development) advantage"},
	34:  {"", "white has a decisive time (development) advantage"},
	35:  {"", "black has a decisive time (development) advantage"},
	36:  {"", "white has the initiative"},
	37:  {"", "black has the initiative"},
	38:  {"", "white has a lasting initiative"},
	39:  {"", "black has a lasting initiative"},
	40:  {"", "white has the attack"},
	41:  {"", "black has the attack"},
	42:  {"", "white has insufficient compensation for material deficit"},
	43:  {"", "black has insufficient compensation for material deficit"},
	44:  {"", "white has sufficient compensation for material deficit"},
	45:  {"", "black has sufficient compensation for material deficit"},
	46:  {"", "white has more than adequate compensation for material deficit"},
	47:  {"", "black has more than adequate compensation for material deficit"},
	48:  {"", "white has a slight center control advantage"},
	49:  {"", "black has a slight center control advantage"},
	50:  {"", "white has a moderate center control advantage"},
	51:  {"", "black has a moderate center control advantage"},
	52:  {"", "white has a decisive center control advantage"},
	53:  {"", "black has a decisive center control advantage"},
	54:  {"", "white has a slight kingside control advantage"},
	55:  {"", "black has a slight kingside control advantage"},
	56:  {"", "white has a moderate kingside control advantage"},
	57:  {"", "black has a moderate kingside control advantage"},
	58:  {"", "white has a decisive kingside control advantage"},
	59:  {"", "black has a decisive kingside control advantage"},
	60:  {"", "white has a slight queenside control advantage"},
	61:  {"", "black has a slight queenside control advantage"},
	62:  {"", "white has a moderate queenside control advantage"},
	63:  {"", "black has a moderate queenside control advantage"},
	64:  {"", "white has a decisive queenside control advantage"},
	65:  {"", "black has a decisive queenside control advantage"},
	66:  {"", "white has a vulnerable first rank"},
	67:  {"", "black has a vulnerable first rank"},
	68:  {"", "white has a well protected first rank"},
	69:  {"", "black has a well protected first rank"},
	70:  {"", "white has a poorly protected king"},
	71:  {"", "black has a poorly protected king"},
	72:  {"", "white has a well protected king"},
	73:  {"", "black has a well protected king"},
	74:  {"", "white has a poorly placed king"},
	75:  {"", "black has a poorly placed king"},
	76:  {"", "white has a well placed king"},
	77:  {"", "black has a well placed king"},
	78:  {"", "white has a very weak pawn structure"},
	79:  {"", "black has a very weak pawn structure"},
	80:  {"", "white has a moderately weak pawn structure"},
	81:  {"", "black has a moderately weak pawn structure"},
	82:  {"", "white has a moderately strong pawn structure"},
	83:  {"", "black has a moderately strong pawn structure"},
	84:  {"", "white has a very strong pawn structure"},
	85:  {"", "black has a very strong pawn structure"},
	86:  {"", "white has poor knight placement"},
	87:  {"", "black has poor knight placement"},
	88:  {"", "white has good knight placement"},
	89:  {"", "black has good knight placement"},
	90:  {"", "white has poor bishop placement"},
	91:  {"", "black has poor bishop placement"},
	92:  {"", "white has good bishop placement"},
	93:  {"", "black has good bishop placement"},
	94:  {"", "white has poor rook placement"},
	95:  {"", "black has poor rook placement"},
	96:  {"", "white has good rook placement"},
	97:  {"", "black has good rook placement"},
	98:  {"", "white has poor queen placement"},
	99:  {"", "black has poor queen placement"},
	100: {"", "white has good queen placement"},
	101: {"", "black has good queen placement"},
	102: {"", "white has poor piece coordination"},
	103: {"", "black has poor piece coordination"},
	104: {"", "white has good piece coordination"},
	105: {"", "black has good piece coordination"},
	106: {"", "white has played the opening very poorly"},
	107: {"", "black has played the opening very poorly"},
	108: {"", "white has played the opening poorly"},
	109: {"", "black has played the opening poorly"},
	110: {"", "white has played the opening well"},
	111: {"", "black has played the opening well"},
	112: {"", "white has played the opening very well"},
	113: {"", "black has played the opening very well"},
	114: {"", "white has played the middlegame very poorly"},
	115: {"", "black has played the middlegame very poorly"},
	116: {"", "white has played the middlegame poorly"},
	117: {"", "black has played the middlegame poorly"},
	118: {"", "white has played the middlegame well"},
	119: {"", "black has played the middlegame well"},
	120: {"", "white has played the middlegame very well"},
	121: {"", "black has played the middlegame very well"},
	122: {"", "white has played the ending very poorly"},
	123: {"", "black has played the ending very poorly"},
	124: {"", "white has played the ending poorly"},
	125: {"", "black has played the ending poorly"},
	126: {"", "white has played the ending well"},
	127: {"", "black has played the ending well"},
	128: {"", "white has played the ending very well"},
	129: {"", "black has played the ending very well"},
	130: {"", "white has slight counterplay"},
	131: {"", "black has slight counterplay"},
	132: {"", "white has moderate counterplay"},
	133: {"", "black has moderate counterplay"},
	134: {"", "white has decisive counterplay"},
	135: {"", "black has decisive counterplay"},
	136: {"", "white has moderate time control pressure"},
	137: {"", "black has moderate time control pressure"},
	138: {"", "white has severe time control pressure"},
	139: {"", "black has severe time control pressure"},
}
